# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8234b70ee94aeaeaf9a504d0e4520246423d5b298416b592a4a4b4a7f6ef5d882d89ce942ad4494b83fc6ac986c8d6747bf6c326defd5020685d7c273df324ee

test:
  secret_key_base: 49945d7456cd1d4bf8d9c2d3fc38ce917df37f1b70b5a92c7fa7a4d600c302a38c314730231fceebf043debaeacb2d01539470856f60d45dc7c680e411b7298a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
